### ISSUE TITLE
Folders deleted

### ISSUE THREAD

**Issue by Programtheweb** [Plac3hold3r/MvxScaffolding#336]
When I create a new project and select an existing folder, all content in that folder is removed.

E.g. Existing structure:
```
D:
  \Source
    \Project1
    \Project2
```

Create a new `MvxScaffolding MvvmCross Forms` project in VS 2017. Leave Name: and Solution name: fields as default. Change Location to D:\Source. 

On 1st screen, set Solution Name as `Test`.

Click through remaining screens leaving all defaults. Application is built and VS 2017 restarts.

Folder now contains:

```
D:
  \Test
  \src
  .editorconfig
  .sln
```

Original Source, Project1, and Project2 folders are wiped without warning.

This differs from normal VS operations where a subfolder based on the project name is automatically created for the generated code.

Workaround is to create a new folder first then put the project there.

**Comment by Plac3hold3r** [comment]
Thanks, @Programtheweb. 

That is somewhat the expected behaviour as MvxScaffolding does a directory delete to remove the default Visual Studio generated files and folders. It should not be replacing the source folder in your example though, so I'll look into that.  Additionally, I will need to have a look and see if MvxScaffolding Visual Studio extension can be smarter around how it cleans up the default Visual Studio template with other existing files/directories that you may not want to be deleted. 

As another workaround, you could make use of generating the template via the dotnet new template CLI which does not suffer the same limitations as the Visual Studio extensions with regards to auto-generated files.

**Comment by Programtheweb** [comment]
I was fortunate that the deleted folders had been recently backed up so I didn't lose anything.

I would suggest creating a sub-folder to put your stuff in and then deleting from there. I would have expected to see (from my original steps):

```
D:
  \Source
    \Project1
    \Project2
    \Test 
       \src
       .editorconfig
       .sln
```

I would also like to add that the UI that you have developed for the add-in is **Excellent**.

**Comment by Plac3hold3r** [comment]
I believe I found the issue. When creating a project in Visual Studio there is a checkbox "Create directory for solution". When the checkbox is not ticked MvxScaffolding was assuming a directory one level too high, which was in your case was D drive root resulting in the deletion of "Source" directory. A fix will be in the next release.

**Comment by Plac3hold3r** [comment]
@Programtheweb version 0.26.0 should resolve your reported issue.
Based on your expected output of 
```
D:
  \Source
    \Project1
    \Project2
    \Test 
       \src
       .editorconfig
       .sln
```
You will need to check "Create directory for solution", which will make sure that the `Test` directory is created. Let me know if there are any other issues.

**Comment by Programtheweb** [comment]
I've just tested the update. It's fixed.

Thank you.

**Comment by Plac3hold3r** [comment]
Thank you @Programtheweb for confirming. Let me know if you come across any other issues.
