### ISSUE TITLE
Exception thrown when trying to run MvxScaffolding

### ISSUE THREAD

**Issue by Edrac** [Plac3hold3r/MvxScaffolding#776]
I just installed the plugin for vs 2019, but as soon as I try to create a project with it, I get this error. Any help would be appreciated.
![image](https://user-images.githubusercontent.com/6632972/84606436-d9617d00-ae6b-11ea-90fb-b166aa66447f.png)

**Comment by Plac3hold3r** [comment]
Hi @Edrac your issue seems similar to #408. Try searching in your Visual Studio installation directory for `MvxScaffolding`. Your directory where to search may look something like

```
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\Extensions
```
Note, if you are not on Community edition, your folder will have a different name.

If you find a match delete the folder that holds the MvxScaffolding dll.

**Comment by Edrac** [comment]
Hi @Plac3hold3r, thank you for your help, I tried to find the dll usuccesfully. I also tried reinstalling visual studio and the plugin, in case another extension was getting in the way, but I still get the same error.
Visual Studio Enterprise 2019 V16.6.2
Any other suggestion you might have?

**Comment by Plac3hold3r** [comment]
@Edrac I have published v1.8.0 which disables the resizing of the windows this is where the exception occurs due to not finding a UI control to check against. I believe this will not solve this issue but will rather reveal more detail to an underline issue.

**Comment by Edrac** [comment]
I got the lastest version, and this is the error I'm getting now
![image](https://user-images.githubusercontent.com/6632972/85243041-48a81580-b406-11ea-828b-d935e7487662.png)

**Comment by Plac3hold3r** [comment]
Thanks @Edrac the issue seems to be the same as the one reported in #408 so deleting the following folder (`elbxuxcf.gui`) should resolve the issue.

```shell
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\Extensions\elbxuxcf.gui
```

![image](https://user-images.githubusercontent.com/13716738/85331405-59c05780-b4d6-11ea-9ef6-877832d2a193.png)

Out of interest how did you install the MvxScaffolding extension? Did you download and manually install or via Visual Studio built-in extension gallery? Did you install it for all Windows users, i.e. an admin install?

As MvxScaffolding is a user scoped extension it installs to an `AppData` location rather than a `Program Files (x86)` used by shared extensions (admin extensions). However, the dlls currently installed in your `Program Files (x86)` extension directory don't seem to be signed so they can't be loaded up. Deleting the directory described above should resolve the issue.

**Comment by Edrac** [comment]
Thank you, and yes, deleting that folder did work.
About your questiosn, the first time I isntalled the extension through the extensions manager in vs, the second time, I downloaded it and installed it manually.

**Comment by Plac3hold3r** [comment]
Awesome, I'm glad to hear that it's work again.
