### ISSUE TITLE
Failed create MvvmCross Native app

### ISSUE THREAD

**Issue by alex-relov** [Plac3hold3r/MvxScaffolding#905]
When using vs 2009 i get an exception:
![image](https://user-images.githubusercontent.com/26199529/103997573-15b84a00-51bd-11eb-92d7-0d20a051c864.png)

**Comment by Plac3hold3r** [comment]
The issue is the same as #776 with the [work around](https://github.com/Plac3hold3r/MvxScaffolding/issues/776#issuecomment-647755706) being to delete the folder in your program directory. Which in your case would be to delete `eibxuxcf.gui`

```text
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\Extensions\elbxuxcf.gui
```

I'm not sure why this issue happens. Did this issue happen just after installing MvxScaffolding for the first time or updating it? Perhaps after a Visual Studio update? Any other noteworthy change you can thing of?

**Comment by Plac3hold3r** [comment]
@alex-relov any luck in implementing the work around?
